# Generated by Django 6.0.6 on 2026-06-26 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('website', 'Website Scraper'), ('email_finder', 'Email Finder'), ('enrichment', 'AI Enrichment')], db_index=True, default='google_maps', max_length=20)),
                ('osm_type', models.CharField(blank=True, max_length=10)),
                ('osm_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=160)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('company_size', models.CharField(blank=True, max_length=80)),
                ('linkedin_url', models.URLField(blank=True, max_length=400)),
                ('email_status', models.CharField(blank=True, max_length=20)),
                ('email_confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('employee_count', models.CharField(blank=True, max_length=80)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('business_category', models.CharField(blank=True, max_length=160)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_score', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='leads.business')),
            ],
            options={
                'verbose_name': 'Enrichment',
                'verbose_name_plural': 'Enrichments',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('website', 'Website Scraper'), ('email_finder', 'Email Finder'), ('enrichment', 'AI Enrichment')], db_index=True, default='google_maps', max_length=20)),
                ('business_type', models.CharField(db_index=True, max_length=160)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('radius_km', models.FloatField(blank=True, null=True)),
                ('max_results', models.PositiveIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=12)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='leads_searc_source_6edee5_idx'), models.Index(fields=['business_type', 'location'], name='leads_searc_busines_e0460c_idx'), models.Index(fields=['-created_at'], name='leads_searc_created_941f58_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=20)),
                ('fmt', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV')], default='xlsx', max_length=8)),
                ('business_type', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='leads.search')),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='leads.search'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='leads_busin_name_bf7486_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category'], name='leads_busin_categor_c3e9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['source'], name='leads_busin_source_ce49b7_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['search', 'name'], name='leads_busin_search__4ea589_idx'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('search', 'osm_type', 'osm_id'), name='unique_business_per_search'),
        ),
    ]
