# Generated by Django 6.0.6 on 2026-06-25 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(db_index=True, max_length=120)),
                ('location', models.CharField(db_index=True, max_length=160)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_type', 'location'], name='leads_searc_busines_e0460c_idx'), models.Index(fields=['-created_at'], name='leads_searc_created_941f58_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='leads.search')),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(blank=True, max_length=10)),
                ('osm_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='leads.search')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='leads_busin_name_bf7486_idx'), models.Index(fields=['category'], name='leads_busin_categor_c3e9bb_idx'), models.Index(fields=['search', 'name'], name='leads_busin_search__4ea589_idx')],
                'constraints': [models.UniqueConstraint(fields=('search', 'osm_type', 'osm_id'), name='unique_business_per_search')],
            },
        ),
    ]
