# Generated by Django 6.0.6 on 2026-06-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_crm_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RemoveIndex(
            model_name='leadactivity',
            name='leads_acti_business_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadactivity',
            name='leads_acti_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='websiteanalysis',
            name='leads_web_url_idx',
        ),
        migrations.RemoveIndex(
            model_name='websiteanalysis',
            name='leads_web_checked_idx',
        ),
        migrations.RemoveIndex(
            model_name='business',
            name='leads_busi_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='business',
            name='leads_busi_contacted_idx',
        ),
        migrations.RemoveField(
            model_name='websiteanalysis',
            name='business',
        ),
        migrations.RemoveField(
            model_name='business',
            name='last_contacted_at',
        ),
        migrations.RemoveField(
            model_name='business',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='business',
            name='status',
        ),
        migrations.DeleteModel(
            name='LeadActivity',
        ),
        migrations.DeleteModel(
            name='WebsiteAnalysis',
        ),
    ]
